[tool.poetry]
name = "dataprep"
version = "0.1.0"
description = ""
authors = ["Weiyuan Wu <doomsplayer@gmail.com>"]
license = "MIT"

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/sfu-db/dataprep"
homepage = "https://github.com/sfu-db/dataprep"

keywords = ["dataprep", "eda"]

[tool.poetry.dependencies]
python = "^3.6"

# Dependencies for EDA
dask = { version = "~2.9", extras = [ "complete" ]}
pandas = "~0.25"
numpy = "~1.17"
scipy = "~1.3"
holoviews = "~1.12"
bokeh = "~1.3"
probscale = "~0.2"

# Dependencies for DataConnector
jsonschema = "~3.1"
requests = "~2.22"
jinja2 = "~2.10"
jsonpath2 = "~0.4"
lxml = "~4.4"

[tool.poetry.dev-dependencies]
pylint = "~2.4"
pytype = "~2019.8"
pytest = "~5.1"
mypy = "~0.740"
black = "19.10b0"
sphinx = "~2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py36', 'py37']
exclude = '''
(
    /(
        \.eggs
    | \.git
    | \.pytype
    | \.pytest_cache
    | build
    | dist
    )/
)
'''
