version: 2.0
jobs:
  check:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - run:
          name: Add python user PATH into PATH
          command: echo "export PATH=$PATH:$HOME/.local/bin" >> $BASH_ENV
      - run: 
          name: Install python tools
          command: pip install --user pipenv
      - setup_remote_docker: 
          docker_layer_caching: true
      - checkout
      - run:
          name: Install dependencies
          command: pipenv install -d
          no_output_timeout: 1200
      - run:
          name: Plot tool versions
          command: pipenv run mypy --version & pipenv run pytype --version && pipenv run pylint --version && pipenv run pytest --version
      - run:
          name: Type check the project
          command: pipenv run pytype dataprep && pipenv run mypy dataprep --strict --ignore-missing-imports
      - run:
          name: Test the project
          command: pipenv run pytest dataprep
      - run:
          name: Style check the project
          command: pipenv run pylint dataprep
workflows:
  version: 2
  build_and_test:
    jobs:
      - check
